### ISSUE TITLE
Echo username in "connection push"?

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/solidfire-cli#11]
At the moment the password isn't echoed (maybe `****`'s?), but it'd be nice to see the username to know whether it's typed properly.
```
# sfcli connection push --mvip 1.1.1.1
Name: somename
Username:
Password:
```

**Comment by ArielCHoffman** [comment]
It would be no trouble to change this at all. I've submitted the question to our PM. Originally the username was obfuscated for security reasons. But if the PM decides that obfuscating the password is enough, we'd be happy to change this for the next version. I have a ticket in the backlog right now so that it will be considered for next release.

**Comment by scaleoutsean** [comment]
Actually that's a valid concern, especially for the "masked" password (as it still reveals the number of keystrokes). 

An argument in favor of echoing the username (even with `*`'s) is that if you mistype either of the two, you need to do it again, and repeatedly entering these things is just as bad (especially in you're not used to the keyboard, such as when working on-site).

**Comment by ArielCHoffman** [comment]
We just chatted about this in standup and someone reminded me that you can type the username in plain text if you want to and you don't have to retype it every time if the security isn't important to you:
sfcli --username admin account list
That command will ask you for a password, but it'll take your username in plain text. If you mistype something, just press the uparrow and try again. You can also pass the password in in this manner. The decision not to echo was designed specifically as a secure alternative for certain users so we're not going to change it in this case.

Thank you!
Ariel

**Comment by scaleoutsean** [comment]
Makes sense, thank you!

**Comment by scaleoutsean** [comment]
Btw one reason why I created this issue is because I got used to it in SF PS Tools:

```
PS /usr/local/share/powershell/Modules/SolidFire> Connect-SFCluster

cmdlet Connect-SFCluster at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
Target: 1.1.1.1
Credential
User: admin
Password for user admin: ********
```
