### ISSUE TITLE
"Cluster listevents" call: how to filter on output

### ISSUE THREAD

**Issue by sl0n** [solidfire/solidfire-cli#20]
Is there a way to only get "apiEvent" events when calling "Cluster listevents" ?

I'd like to have the same functionality in CLI as in GUI, where I can filter by certain field(s).

Thanks!

**Comment by mblessing** [comment]
Hi sl0n,

The solidfire-cli does not have the ability to filter the events returned by cluster listevents, but there is a way you can probably get just the events you want.

The -j switch of sfcli causes it to output the results in json format.

There is an open-source, command-line json processor that can then manipulate that json in a variety of ways, including to filter it by event type.

See https://stedolan.github.io/jq/ for more info on jq and to download the executable for Windows, Mac, or Linux.  There is no installation or dependencies, just a single executable to put somewhere in your path.

I tried it out on Windows in PowerShell and was able to use the following command to get just the events of apiEvent type.

sfcli -j cluster listevents | jq '.result.events[] | select(.eventInfoType == """apiEvent""")'

The exact syntax of the quotes might be different if you are using a different shell.

The jq processor looks very powerful.  There are probably some other interesting ways it could be used with sfcli output.

--Michael Blessing

**Comment by sl0n** [comment]
@mblessing thanks, that works pretty nicely. I have a cluster with > 1K of volumes and > 1K VAGs, and it makes SF's web UI pretty sad ..
