### ISSUE TITLE
createsupportbundle results in timeout ERROR

### ISSUE THREAD

**Issue by labazza** [solidfire/solidfire-cli#28]
hi, if i run:

     sfcli --mvip <cluster_mvip> --username admin --password <password> -q 442 cluster createsupportbundle

I get a timeout error:

    element.cli.cli: in cmd_cluster.py at 680 - ERROR: HTTPSConnectionPool(host='cluster_mvip', port=442): Read timed out. (read timeout=30)

but the API call seems processed since if i run the same command again, i get:

        element.cli.cli: in cmd_cluster.py at 680 - ERROR: 500 xAPINotPermitted Concurrent bundle creation is not allowed

**Comment by Salmanius** [comment]
Hello labazza, 

You helped us identify a problem with our code. Good news is we have a work around. (1500 is just the default timeout for the API that the sfcli talks to)
`sfcli --mvip <cluster_mvip> --username admin --password <password> -q 442 --timeout 1500 cluster createsupportbundle`

Or alternatively if you are saving a connection for later use make sure to give a large enough timeout to handle the createsupportbundle call (by default 1500).

Make sure the `--timeout X` is on the left side of the cluster keyword or it will relate to the createsupportbundle timeout which won't help this.

**Comment by labazza** [comment]
yes it worked increasing the timeout. thanks.
it would be feature+ if it lets you directly dowload the bundle

**Comment by ahaid** [comment]
This is working as designed. The user should make sure to adjust the connection timeout based on the expected duration of the calls being made on that connection.
