### ISSUE TITLE
Enhancement request: add version info

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/solidfire-cli#7]
* solidfire-cli (1.4.0.339)
* solidfire-sdk-python (1.4.0.271)

`-v|--version` can't be used to get sfcli version info because it's taken, but ` sfcli --help` also doesn't have it, so the only way I found is `pip list`. There should probably be a better way.

Can sfcli version info be added to `sfcli --help` output? Or maybe `sfcli -V`?

**Comment by ahaid** [comment]
Great request. I created Jira ticket SDK-845 to address this and put it in the backlog. We'll get it into the next release (1.5) and update this issue when it's done.

**Comment by scaleoutsean** [comment]
In v1.5 I can't find it in `--help` output so this is an improvement.

```
(pythoncli) user@box:~$ sfcli --help | more
Usage: sfcli [OPTIONS] COMMAND [ARGS]...

  Welcome to the SolidFire Command Line Interface 1.5.0.29.
```
